export const LOAD_DATA = 'LOAD_DATA';
export const LOAD_ERROR = 'LOAD_ERROR';

export const CHANGE_USERS_DROPDOWN = 'CHANGE_USERS_DROPDOWN';

export const SET_DRAGGABLE_ITEM = 'SET_DRAGGABLE_ITEM';
export const APPEND_DRAGGABLE_ITEM = 'APPEND_DRAGGABLE_ITEM';
export const DELETE_FAVORITE_USER = 'DELETE_FAVORITE_USER';
